obj: # Hourly
  bg_opa: TRANSP
  border_opa: TRANSP
  grid_cell_row_pos: $row_pos
  grid_cell_row_span: $row_span
  grid_cell_column_pos: $column_pos
  grid_cell_column_span: $column_span
  grid_cell_x_align: STRETCH
  grid_cell_y_align: STRETCH
  # outline_width: 1
  pad_all: 0
  layout:
    type: grid
    grid_columns: [FR(1),FR(1),FR(1),FR(1),FR(1),FR(1),FR(1),FR(1)]
    grid_rows: [FR(1), FR(2), FR(1)]
    pad_column: 0
    pad_row: 0
  widgets:
    - label:
        grid_cell_column_pos: 0
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F1455"
        pad_all: 0
        text_align: CENTER
        id: lbl_hourly_hour_1
        # outline_width: 1
    - label:
        grid_cell_column_pos: 1
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F1456"
        pad_all: 0
        text_align: CENTER
        id: lbl_hourly_hour_2
        # outline_width: 1
    - label:
        grid_cell_column_pos: 2
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F144B"
        pad_all: 0
        text_align: CENTER
        id: lbl_hourly_hour_3
        # outline_width: 1
    - label:
        grid_cell_column_pos: 3
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F144C"
        text_align: CENTER
        id: lbl_hourly_hour_4
        # outline_width: 1
    - label:
        grid_cell_column_pos: 4
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F144D"
        text_align: CENTER
        id: lbl_hourly_hour_5
        # outline_width: 1
    - label:
        grid_cell_column_pos: 5
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F144E"
        text_align: CENTER
        id: lbl_hourly_hour_6
        # outline_width: 1
    - label:
        grid_cell_column_pos: 6
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F144F"
        text_align: CENTER
        pad_all: 0
        id: lbl_hourly_hour_7
        # outline_width: 1
    - label:
        grid_cell_column_pos: 7
        grid_cell_row_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_icons
        text: "\U000F1450"
        text_align: CENTER
        id: lbl_hourly_hour_8
        # outline_width: 1
    
    # Hourly conditions
    - label:
        grid_cell_column_pos: 0
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_1
        # outline_width: 1
    - label:
        grid_cell_column_pos: 1
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_2
        # outline_width: 1
    - label:
        grid_cell_column_pos: 2
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_3
        # outline_width: 1
    - label:
        grid_cell_column_pos: 3
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_4
        # outline_width: 1
    - label:
        grid_cell_column_pos: 4
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_5
        # outline_width: 1
    - label:
        grid_cell_column_pos: 5
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_6
        # outline_width: 1
    - label:
        grid_cell_column_pos: 6
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_7
        # outline_width: 1
    - label:
        grid_cell_column_pos: 7
        grid_cell_row_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_font: font_current_conditions_tiny
        text_align: CENTER
        text: "\U000F14E4"
        id: lbl_hourly_condition_8
        # outline_width: 1
    
    - label:
        grid_cell_column_pos: 0
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_1
    - label:
        grid_cell_column_pos: 1
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_2
    - label:
        grid_cell_column_pos: 2
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_3
    - label:
        grid_cell_column_pos: 3
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_4
    - label:
        grid_cell_column_pos: 4
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_5
    - label:
        grid_cell_column_pos: 5
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_6
    - label:
        grid_cell_column_pos: 6
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_7
    - label:
        grid_cell_column_pos: 7
        grid_cell_row_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: CENTER
        text_align: CENTER
        text: "16°"
        id: lbl_hourly_temp_8
