obj: # 5 Day
  bg_opa: TRANSP
  border_opa: TRANSP
  grid_cell_row_pos: $row_pos
  grid_cell_row_span: $row_span
  grid_cell_column_pos: $column_pos
  grid_cell_column_span: $column_span
  grid_cell_x_align: STRETCH
  grid_cell_y_align: STRETCH
  layout:
    type: grid
    grid_rows: [FR(15), FR(35), FR(15), FR(15)]
    grid_columns: [FR(20), FR(20), FR(20), FR(20), FR(20)]
  widgets:
    - label:
        grid_cell_row_pos: 0
        grid_cell_column_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_1_day
        text_align: CENTER
        text: "Sun"
    - label:
        grid_cell_row_pos: 0
        grid_cell_column_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_2_day
        text_align: CENTER
        text: "Mon"
    - label:
        grid_cell_row_pos: 0
        grid_cell_column_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_3_day
        text_align: CENTER
        text: "Tue"
    - label:
        grid_cell_row_pos: 0
        grid_cell_column_pos: 3
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_4_day
        text_align: CENTER
        text: "Wed"
    - label:
        grid_cell_row_pos: 0
        grid_cell_column_pos: 4
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_5_day
        text_align: CENTER
        text: "Thu"
      
    - label:
        grid_cell_row_pos: 1
        grid_cell_column_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_condition_1
        text_font: font_current_conditions_small
        text: "\U000F14E4"
    - label:
        grid_cell_row_pos: 1
        grid_cell_column_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_condition_2
        text_font: font_current_conditions_small
        text: "\U000F14E4"
    - label:
        grid_cell_row_pos: 1
        grid_cell_column_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_condition_3
        text_font: font_current_conditions_small
        text: "\U000F14E4"
    - label:
        grid_cell_row_pos: 1
        grid_cell_column_pos: 3
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_condition_4
        text_font: font_current_conditions_small
        text: "\U000F14E4"
    - label:
        grid_cell_row_pos: 1
        grid_cell_column_pos: 4
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        id: lbl_daily_condition_5
        text_font: font_current_conditions_small
        text: "\U000F14E4"

    - label:
        grid_cell_row_pos: 2
        grid_cell_column_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_high_1
        text_font: font_small_medium
        text: "--°"
    - label:
        grid_cell_row_pos: 2
        grid_cell_column_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_high_2
        text_font: font_small_medium
        text: "--°"
    - label:
        grid_cell_row_pos: 2
        grid_cell_column_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_high_3
        text_font: font_small_medium
        text: "--°"
    - label:
        grid_cell_row_pos: 2
        grid_cell_column_pos: 3
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_high_4
        text_font: font_small_medium
        text: "--°"
    - label:
        grid_cell_row_pos: 2
        grid_cell_column_pos: 4
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_high_5
        text_font: font_small_medium
        text: "--°"
    
    - label:
        grid_cell_row_pos: 3
        grid_cell_column_pos: 0
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_low_1
        text_font: font_small
        text: "--°"
    - label:
        grid_cell_row_pos: 3
        grid_cell_column_pos: 1
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_low_2
        text_font: font_small
        text: "--°"
    - label:
        grid_cell_row_pos: 3
        grid_cell_column_pos: 2
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_low_3
        text_font: font_small
        text: "--°"
    - label:
        grid_cell_row_pos: 3
        grid_cell_column_pos: 3
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_low_4
        text_font: font_small
        text: "--°"
    - label:
        grid_cell_row_pos: 3
        grid_cell_column_pos: 4
        grid_cell_x_align: STRETCH
        grid_cell_y_align: STRETCH
        text_align: CENTER
        id: lbl_daily_low_5
        text_font: font_small
        text: "--°"
