---
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  unit_system: imperial
  time_zone: America/Detroit
  country: US
  currency: USD

ecobee:
  api_key: !secret ecobee_key

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
