substitutions:
  device_comment: "Sonoff Basic"

esp8266:
  board: esp01_1m

output:
  - id: relay
    platform: gpio
    pin:
      number: GPIO12

status_led:
  pin:
    number: GPIO13
    inverted: yes

binary_sensor:
  - platform: gpio
    id: button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "$friendly_name Button"
