substitutions:
  name: poe-bluetooth-proxy
  friendly_name: Bluetooth Proxy
  api_encryption_key: !secret poe_bluetooth_proxy_encryption_key
  ota_password: !secret poe_bluetooth_proxy_ota_password

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: "LilyGo T-ETH-Lite ESP32	RTL9201"

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

ethernet:
  type: W5500
  clk_pin: GPIO10
  mosi_pin: GPIO12
  miso_pin: GPIO11
  cs_pin: GPIO09
  interrupt_pin: GPIO13
  reset_pin: GPIO14

<<: !include common/no-wifi.yaml

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: Safe Mode Boot
    entity_category: diagnostic
