substitutions:
  display_width: 800
  display_height: 480
  api_encryption_key: !secret trmnl_encryption_key

esphome:
  name: trmnl-host

host:

packages:
  api: !include ./common/api.yaml
  log: !include ./common/logging.yaml
  time: !include ./components/homeassistant-time.yaml
  display: !include ./ui/displays/waveshare-sdl.yaml
  ui: !include 
    file: ./ui/trmnl.yaml
    vars:
      display_white: "FFFFFF"
      display_black: "000000"
