substitutions:
  name: trmnl
  friendly_name: "TRMNL"
  device_comment: "TRMNL 7.5 (OG) DIY Kit"
  api_encryption_key: !secret trmnl_encryption_key
  ota_password: !secret trmnl_ota_password
  spi_clk: GPIO7
  spi_mosi: GPIO9
  button1_pin: 
    number: GPIO02
    mode: INPUT_PULLUP
    inverted: true
  button2_pin: 
    number: GPIO03
    mode: INPUT_PULLUP
    inverted: true
  button3_pin:
    number: GPIO05
    mode: INPUT_PULLUP
    inverted: true

packages:
  base: !include ./devices/xiao-esp32-s3-plus.yaml
  spi: !include ./components/spi.yaml
  time: !include ./components/ntp.yaml
  display: !include ./ui/displays/waveshare-epaper.yaml
  ui: !include 
    file: ./ui/trmnl.yaml
    vars:
      display_white: "000000"
      display_black: "FFFFFF"
